class Session < ApplicationRecord
    has_secure_password
    validates_presence_of :password

    def authenticate(password)
        # Salts generated by generate_salt are always 29 chars long.
        salt = password_digest[0..28]
        hashed = BCrypt::Engine::hash_secret(password, salt)
        return nil unless (salt + hashed) == self.password_digest
    end

end
